# Generated by Django 5.2.1 on 2025-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(choices=[('30 minutes', '30 minutes'), ('1 hour', '1 hour'), ('1.5 hours', '1.5 hours')], max_length=20),
        ),
    ]
